- name: vm configuration
  hosts: all

  tasks:
    - name: "install docker dependencies"
      apt:
        name: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common', 'python-pip' ]
        update_cache: yes
      become: yes
      become_method: sudo

    - name: Add Docker GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg
      become: yes
      become_method: sudo
    - name: "Add Docker repository"
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      become: yes
      become_method: sudo
    - name: "install specific version of docker-ce"
      apt:
        name: "docker-ce=5:19.03.13~3-0~ubuntu-bionic"
        update_cache: yes
      become: yes
      become_method: sudo
    - name: "install python packages"
      pip:
        name: docker-py

    - name: use docker without sudo
      user:
        name: vagrant
        append: yes
        groups: docker
      become: yes
      become_method: sudo
    - name: Build image and with build args
      docker_image:
        name: jenkinsik
        build:
          path: /vagrant/jenkins
        source: build
    - name: start jenkins container
      docker_container:
        name: jenkins_server
        image: jenkinsik
        state: started
        ports:
        - "8080:8080"
        env:
          USER: "admin"
          PASSWORD: "admin"





